### ISSUE TITLE
Unable to install genie.webdriver package

### ISSUE THREAD

**Issue by extsoft** [CiscoDevNet/pyats-gui-sample#2]
There is a `genie.webdriver` package in the README.md file. If it tries to install it, I have the following error:
```bash
$ pip install genie.webdriver
Collecting genie.webdriver
  Could not find a version that satisfies the requirement genie.webdriver (from versions: )
No matching distribution found for genie.webdriver
```

Is this package available?

**Comment by jeaubin** [comment]
Thanks for reporting it! 

We will be releasing it soon.  Will let you know as soon it is released.

**Comment by jeaubin** [comment]
It is planned for release October 1st.  Do you need it before this date?  If so, we can get it released before this.

**Comment by extsoft** [comment]
@jeaubin It will be great to have a copy of the documentation. I want to understand which capabilities this package has. And if you can release it earlier, it will be really great.

**Comment by supertylerc** [comment]
@jeaubin where did this end up?  Looks like there's still no `genie.webdriver`.

**Comment by jeaubin** [comment]
@supertylerc @extsoft We had to delay the release until start of next year.  However i released the documentation yesterday so you could take a look at it ! 

https://developer.cisco.com/site/pyats/docs/packages/

Go to the WebDriver page.

**Comment by jeaubin** [comment]
Hi @supertylerc @extsoft   I've just released genie.webdriver

pip install genie.webdriver

And you can find the documentation of it here: https://pubhub.devnetcloud.com/media/pyats-packages/docs/webdriver/index.html

**Comment by extsoft** [comment]
@jeaubin close the issue as it is solved.
